package Wayfinder;

public class connectionType {

	private String Name;
	private String ConnectionString;
	private double Speed;
	
	/**
	 * Creates a type of Connection
	 * @param Name Name of the connection type
	 * @param connectionString Connection string that will be used to spit a route as a string. IE: "-[TYPE]->".
	 * @param Speed Speed of this type of connection (Preferable in Distance Unit/Second)
	 */
	public connectionType(String Name, String connectionString, double Speed) {
		this.Name=Name;
		this.ConnectionString=connectionString;
		this.Speed=Speed;
	}

	public String getName() {return Name;}
	public String getConnectionString() {return ConnectionString;}
	public double getSpeed() {return Speed;}

	//Autogenerated equals funcition.
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		connectionType other = (connectionType) obj;
		if (ConnectionString == null) {
			if (other.ConnectionString != null)
				return false;
		} else if (!ConnectionString.equals(other.ConnectionString))
			return false;
		if (Name == null) {
			if (other.Name != null)
				return false;
		} else if (!Name.equals(other.Name))
			return false;
		return true;
	}
	
	
}
