package Wayfinder;

public class connectionType {

	private String Name;
	private String ConnectionString;
	
	public connectionType(String Name, String connectionString) {
		this.Name=Name;
		this.ConnectionString=connectionString;
	}

	public String getName() {return Name;}
	public String getConnectionString() {return ConnectionString;}
	

	//Autogenerated equals funcition.
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		connectionType other = (connectionType) obj;
		if (ConnectionString == null) {
			if (other.ConnectionString != null)
				return false;
		} else if (!ConnectionString.equals(other.ConnectionString))
			return false;
		if (Name == null) {
			if (other.Name != null)
				return false;
		} else if (!Name.equals(other.Name))
			return false;
		return true;
	}
	
	
}
